import React from 'react'

export default function Home(props) {
  return (
    <div>
      <h1>Home Page</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque!</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque!</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque!</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis quibusdam deleniti sequi, itaque facere consequuntur enim temporibus est vitae maxime, cum error accusantium praesentium perspiciatis voluptatum! Veniam animi ullam eaque!</p>
    </div>
  )
}